name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.14.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.14.0
        cache: 'npm'
    - run: npm ci
    - run: npm run build --force
    - run: npm test
    - uses: actions/upload-artifact@v4
      with:
        name: compiled-code
        path: |
          dist
          Dockerfile
          compose.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.DEPLOY_SERVER }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.USER_PWD }}
            port: ${{ secrets.PORT }}
            script: |
              cd /opt/polytech-orchestra-bot
              git pull
              chmod +x install_script.sh
              ./install_script.sh
